import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { BlogTag } from "@/types/blog";
import { toast } from "sonner";

export function useBlogTags() {
  return useQuery({
    queryKey: ['blog-tags'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('blog_tags')
        .select('*')
        .order('name');

      if (error) throw error;

      // Get post counts
      const { data: counts } = await supabase
        .from('blog_post_tags')
        .select('tag_id');

      const countMap = new Map<string, number>();
      counts?.forEach(t => {
        countMap.set(t.tag_id, (countMap.get(t.tag_id) || 0) + 1);
      });

      return data.map(tag => ({
        ...tag,
        post_count: countMap.get(tag.id) || 0,
      })) as BlogTag[];
    },
  });
}

export function useCreateBlogTag() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: { name: string }) => {
      // Slug is auto-generated by trigger
      const slug = data.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const { data: tag, error } = await supabase
        .from('blog_tags')
        .insert({ ...data, slug })
        .select()
        .single();

      if (error) throw error;
      return tag;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-tags'] });
      toast.success('Tag created');
    },
    onError: (error) => {
      toast.error(`Failed to create tag: ${error.message}`);
    },
  });
}

export function useUpdateBlogTag() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: { name: string } }) => {
      const { data: tag, error } = await supabase
        .from('blog_tags')
        .update(data)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return tag;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-tags'] });
      toast.success('Tag updated');
    },
    onError: (error) => {
      toast.error(`Failed to update tag: ${error.message}`);
    },
  });
}

export function useDeleteBlogTag() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('blog_tags')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-tags'] });
      toast.success('Tag deleted');
    },
    onError: (error) => {
      toast.error(`Failed to delete tag: ${error.message}`);
    },
  });
}
