/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CreateFromMenerioRouteImport } from './routes/create-from-menerio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsNewRouteImport } from './routes/collections/new'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PromptKitsNewRouteImport } from './routes/prompt-kits/new'
import { Route as PromptsNewRouteImport } from './routes/prompts/new'
import { Route as PromptsWizardRouteImport } from './routes/prompts/wizard'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as TeamJoinRouteImport } from './routes/team/join'
import { Route as WorkflowsNewRouteImport } from './routes/workflows/new'
import { Route as BlogAdminIndexRouteImport } from './routes/blog/admin/index'
import { Route as BlogAdminCategoriesRouteImport } from './routes/blog/admin/categories'
import { Route as BlogAdminMediaRouteImport } from './routes/blog/admin/media'
import { Route as BlogAdminTagsRouteImport } from './routes/blog/admin/tags'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category/$slug'
import { Route as BlogTagSlugRouteImport } from './routes/blog/tag/$slug'
import { Route as CollectionsIdIndexRouteImport } from './routes/collections/$id.index'
import { Route as CollectionsIdEditRouteImport } from './routes/collections/$id.edit'
import { Route as LibrarySlugEditRouteImport } from './routes/library/$slug.edit'
import { Route as LibrarySlugVersionsRouteImport } from './routes/library/$slug.versions'
import { Route as PromptKitsSlugIndexRouteImport } from './routes/prompt-kits/$slug.index'
import { Route as PromptKitsSlugEditRouteImport } from './routes/prompt-kits/$slug.edit'
import { Route as PromptsSlugIndexRouteImport } from './routes/prompts/$slug.index'
import { Route as PromptsSlugEditRouteImport } from './routes/prompts/$slug.edit'
import { Route as SkillsSlugIndexRouteImport } from './routes/skills/$slug.index'
import { Route as SkillsSlugEditRouteImport } from './routes/skills/$slug.edit'
import { Route as TeamIdActivityRouteImport } from './routes/team/$id.activity'
import { Route as TeamIdSettingsRouteImport } from './routes/team/$id.settings'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username.index'
import { Route as UUsernameActivityRouteImport } from './routes/u/$username.activity'
import { Route as WorkflowsSlugIndexRouteImport } from './routes/workflows/$slug.index'
import { Route as WorkflowsSlugEditRouteImport } from './routes/workflows/$slug.edit'
import { Route as BlogAdminPostsIndexRouteImport } from './routes/blog/admin/posts/index'
import { Route as BlogAdminPostsNewRouteImport } from './routes/blog/admin/posts/new'
import { Route as BlogAdminPostsIdEditRouteImport } from './routes/blog/admin/posts/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateFromMenerioRoute = CreateFromMenerioRouteImport.update({
  id: '/create-from-menerio',
  path: '/create-from-menerio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptKitsNewRoute = PromptKitsNewRouteImport.update({
  id: '/prompt-kits/new',
  path: '/prompt-kits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsNewRoute = PromptsNewRouteImport.update({
  id: '/prompts/new',
  path: '/prompts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsWizardRoute = PromptsWizardRouteImport.update({
  id: '/prompts/wizard',
  path: '/prompts/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamJoinRoute = TeamJoinRouteImport.update({
  id: '/team/join',
  path: '/team/join',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminIndexRoute = BlogAdminIndexRouteImport.update({
  id: '/blog/admin/',
  path: '/blog/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminCategoriesRoute = BlogAdminCategoriesRouteImport.update({
  id: '/blog/admin/categories',
  path: '/blog/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminMediaRoute = BlogAdminMediaRouteImport.update({
  id: '/blog/admin/media',
  path: '/blog/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminTagsRoute = BlogAdminTagsRouteImport.update({
  id: '/blog/admin/tags',
  path: '/blog/admin/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdIndexRoute = CollectionsIdIndexRouteImport.update({
  id: '/collections/$id/',
  path: '/collections/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdEditRoute = CollectionsIdEditRouteImport.update({
  id: '/collections/$id/edit',
  path: '/collections/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugEditRoute = LibrarySlugEditRouteImport.update({
  id: '/library/$slug/edit',
  path: '/library/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugVersionsRoute = LibrarySlugVersionsRouteImport.update({
  id: '/library/$slug/versions',
  path: '/library/$slug/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptKitsSlugIndexRoute = PromptKitsSlugIndexRouteImport.update({
  id: '/prompt-kits/$slug/',
  path: '/prompt-kits/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptKitsSlugEditRoute = PromptKitsSlugEditRouteImport.update({
  id: '/prompt-kits/$slug/edit',
  path: '/prompt-kits/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugIndexRoute = PromptsSlugIndexRouteImport.update({
  id: '/prompts/$slug/',
  path: '/prompts/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugEditRoute = PromptsSlugEditRouteImport.update({
  id: '/prompts/$slug/edit',
  path: '/prompts/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugIndexRoute = SkillsSlugIndexRouteImport.update({
  id: '/skills/$slug/',
  path: '/skills/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugEditRoute = SkillsSlugEditRouteImport.update({
  id: '/skills/$slug/edit',
  path: '/skills/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdActivityRoute = TeamIdActivityRouteImport.update({
  id: '/team/$id/activity',
  path: '/team/$id/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdSettingsRoute = TeamIdSettingsRouteImport.update({
  id: '/team/$id/settings',
  path: '/team/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameActivityRoute = UUsernameActivityRouteImport.update({
  id: '/u/$username/activity',
  path: '/u/$username/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSlugIndexRoute = WorkflowsSlugIndexRouteImport.update({
  id: '/workflows/$slug/',
  path: '/workflows/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSlugEditRoute = WorkflowsSlugEditRouteImport.update({
  id: '/workflows/$slug/edit',
  path: '/workflows/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminPostsIndexRoute = BlogAdminPostsIndexRouteImport.update({
  id: '/blog/admin/posts/',
  path: '/blog/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminPostsNewRoute = BlogAdminPostsNewRouteImport.update({
  id: '/blog/admin/posts/new',
  path: '/blog/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminPostsIdEditRoute = BlogAdminPostsIdEditRouteImport.update({
  id: '/blog/admin/posts/$id/edit',
  path: '/blog/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookies': typeof CookiesRoute
  '/create-from-menerio': typeof CreateFromMenerioRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/new': typeof CollectionsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt-kits/new': typeof PromptKitsNewRoute
  '/prompts/new': typeof PromptsNewRoute
  '/prompts/wizard': typeof PromptsWizardRoute
  '/skills/new': typeof SkillsNewRoute
  '/team/join': typeof TeamJoinRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/blog/admin/categories': typeof BlogAdminCategoriesRoute
  '/blog/admin/media': typeof BlogAdminMediaRoute
  '/blog/admin/tags': typeof BlogAdminTagsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/library/$slug/edit': typeof LibrarySlugEditRoute
  '/library/$slug/versions': typeof LibrarySlugVersionsRoute
  '/prompt-kits/$slug/edit': typeof PromptKitsSlugEditRoute
  '/prompts/$slug/edit': typeof PromptsSlugEditRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
  '/team/$id/activity': typeof TeamIdActivityRoute
  '/team/$id/settings': typeof TeamIdSettingsRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/workflows/$slug/edit': typeof WorkflowsSlugEditRoute
  '/blog/admin/': typeof BlogAdminIndexRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/prompt-kits/$slug/': typeof PromptKitsSlugIndexRoute
  '/prompts/$slug/': typeof PromptsSlugIndexRoute
  '/skills/$slug/': typeof SkillsSlugIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/workflows/$slug/': typeof WorkflowsSlugIndexRoute
  '/blog/admin/posts/new': typeof BlogAdminPostsNewRoute
  '/blog/admin/posts/': typeof BlogAdminPostsIndexRoute
  '/blog/admin/posts/$id/edit': typeof BlogAdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookies': typeof CookiesRoute
  '/create-from-menerio': typeof CreateFromMenerioRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/new': typeof CollectionsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt-kits/new': typeof PromptKitsNewRoute
  '/prompts/new': typeof PromptsNewRoute
  '/prompts/wizard': typeof PromptsWizardRoute
  '/skills/new': typeof SkillsNewRoute
  '/team/join': typeof TeamJoinRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/blog/admin/categories': typeof BlogAdminCategoriesRoute
  '/blog/admin/media': typeof BlogAdminMediaRoute
  '/blog/admin/tags': typeof BlogAdminTagsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/library/$slug/edit': typeof LibrarySlugEditRoute
  '/library/$slug/versions': typeof LibrarySlugVersionsRoute
  '/prompt-kits/$slug/edit': typeof PromptKitsSlugEditRoute
  '/prompts/$slug/edit': typeof PromptsSlugEditRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
  '/team/$id/activity': typeof TeamIdActivityRoute
  '/team/$id/settings': typeof TeamIdSettingsRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/workflows/$slug/edit': typeof WorkflowsSlugEditRoute
  '/blog/admin': typeof BlogAdminIndexRoute
  '/collections/$id': typeof CollectionsIdIndexRoute
  '/prompt-kits/$slug': typeof PromptKitsSlugIndexRoute
  '/prompts/$slug': typeof PromptsSlugIndexRoute
  '/skills/$slug': typeof SkillsSlugIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/workflows/$slug': typeof WorkflowsSlugIndexRoute
  '/blog/admin/posts/new': typeof BlogAdminPostsNewRoute
  '/blog/admin/posts': typeof BlogAdminPostsIndexRoute
  '/blog/admin/posts/$id/edit': typeof BlogAdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookies': typeof CookiesRoute
  '/create-from-menerio': typeof CreateFromMenerioRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/impressum': typeof ImpressumRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collections/new': typeof CollectionsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/prompt-kits/new': typeof PromptKitsNewRoute
  '/prompts/new': typeof PromptsNewRoute
  '/prompts/wizard': typeof PromptsWizardRoute
  '/skills/new': typeof SkillsNewRoute
  '/team/join': typeof TeamJoinRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/blog/admin/categories': typeof BlogAdminCategoriesRoute
  '/blog/admin/media': typeof BlogAdminMediaRoute
  '/blog/admin/tags': typeof BlogAdminTagsRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/library/$slug/edit': typeof LibrarySlugEditRoute
  '/library/$slug/versions': typeof LibrarySlugVersionsRoute
  '/prompt-kits/$slug/edit': typeof PromptKitsSlugEditRoute
  '/prompts/$slug/edit': typeof PromptsSlugEditRoute
  '/skills/$slug/edit': typeof SkillsSlugEditRoute
  '/team/$id/activity': typeof TeamIdActivityRoute
  '/team/$id/settings': typeof TeamIdSettingsRoute
  '/u/$username/activity': typeof UUsernameActivityRoute
  '/workflows/$slug/edit': typeof WorkflowsSlugEditRoute
  '/blog/admin/': typeof BlogAdminIndexRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
  '/prompt-kits/$slug/': typeof PromptKitsSlugIndexRoute
  '/prompts/$slug/': typeof PromptsSlugIndexRoute
  '/skills/$slug/': typeof SkillsSlugIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/workflows/$slug/': typeof WorkflowsSlugIndexRoute
  '/blog/admin/posts/new': typeof BlogAdminPostsNewRoute
  '/blog/admin/posts/': typeof BlogAdminPostsIndexRoute
  '/blog/admin/posts/$id/edit': typeof BlogAdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/cookies'
    | '/create-from-menerio'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/impressum'
    | '/privacy'
    | '/rss.xml'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/collections/new'
    | '/profile/edit'
    | '/prompt-kits/new'
    | '/prompts/new'
    | '/prompts/wizard'
    | '/skills/new'
    | '/team/join'
    | '/workflows/new'
    | '/blog/'
    | '/collections/'
    | '/library/'
    | '/blog/admin/categories'
    | '/blog/admin/media'
    | '/blog/admin/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/collections/$id/edit'
    | '/library/$slug/edit'
    | '/library/$slug/versions'
    | '/prompt-kits/$slug/edit'
    | '/prompts/$slug/edit'
    | '/skills/$slug/edit'
    | '/team/$id/activity'
    | '/team/$id/settings'
    | '/u/$username/activity'
    | '/workflows/$slug/edit'
    | '/blog/admin/'
    | '/collections/$id/'
    | '/prompt-kits/$slug/'
    | '/prompts/$slug/'
    | '/skills/$slug/'
    | '/u/$username/'
    | '/workflows/$slug/'
    | '/blog/admin/posts/new'
    | '/blog/admin/posts/'
    | '/blog/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/cookies'
    | '/create-from-menerio'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/impressum'
    | '/privacy'
    | '/rss.xml'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/collections/new'
    | '/profile/edit'
    | '/prompt-kits/new'
    | '/prompts/new'
    | '/prompts/wizard'
    | '/skills/new'
    | '/team/join'
    | '/workflows/new'
    | '/blog'
    | '/collections'
    | '/library'
    | '/blog/admin/categories'
    | '/blog/admin/media'
    | '/blog/admin/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/collections/$id/edit'
    | '/library/$slug/edit'
    | '/library/$slug/versions'
    | '/prompt-kits/$slug/edit'
    | '/prompts/$slug/edit'
    | '/skills/$slug/edit'
    | '/team/$id/activity'
    | '/team/$id/settings'
    | '/u/$username/activity'
    | '/workflows/$slug/edit'
    | '/blog/admin'
    | '/collections/$id'
    | '/prompt-kits/$slug'
    | '/prompts/$slug'
    | '/skills/$slug'
    | '/u/$username'
    | '/workflows/$slug'
    | '/blog/admin/posts/new'
    | '/blog/admin/posts'
    | '/blog/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/cookies'
    | '/create-from-menerio'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/impressum'
    | '/privacy'
    | '/rss.xml'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/collections/new'
    | '/profile/edit'
    | '/prompt-kits/new'
    | '/prompts/new'
    | '/prompts/wizard'
    | '/skills/new'
    | '/team/join'
    | '/workflows/new'
    | '/blog/'
    | '/collections/'
    | '/library/'
    | '/blog/admin/categories'
    | '/blog/admin/media'
    | '/blog/admin/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/collections/$id/edit'
    | '/library/$slug/edit'
    | '/library/$slug/versions'
    | '/prompt-kits/$slug/edit'
    | '/prompts/$slug/edit'
    | '/skills/$slug/edit'
    | '/team/$id/activity'
    | '/team/$id/settings'
    | '/u/$username/activity'
    | '/workflows/$slug/edit'
    | '/blog/admin/'
    | '/collections/$id/'
    | '/prompt-kits/$slug/'
    | '/prompts/$slug/'
    | '/skills/$slug/'
    | '/u/$username/'
    | '/workflows/$slug/'
    | '/blog/admin/posts/new'
    | '/blog/admin/posts/'
    | '/blog/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CookiesRoute: typeof CookiesRoute
  CreateFromMenerioRoute: typeof CreateFromMenerioRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRoute
  ImpressumRoute: typeof ImpressumRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CollectionsNewRoute: typeof CollectionsNewRoute
  ProfileEditRoute: typeof ProfileEditRoute
  PromptKitsNewRoute: typeof PromptKitsNewRoute
  PromptsNewRoute: typeof PromptsNewRoute
  PromptsWizardRoute: typeof PromptsWizardRoute
  SkillsNewRoute: typeof SkillsNewRoute
  TeamJoinRoute: typeof TeamJoinRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  BlogAdminCategoriesRoute: typeof BlogAdminCategoriesRoute
  BlogAdminMediaRoute: typeof BlogAdminMediaRoute
  BlogAdminTagsRoute: typeof BlogAdminTagsRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
  CollectionsIdEditRoute: typeof CollectionsIdEditRoute
  LibrarySlugEditRoute: typeof LibrarySlugEditRoute
  LibrarySlugVersionsRoute: typeof LibrarySlugVersionsRoute
  PromptKitsSlugEditRoute: typeof PromptKitsSlugEditRoute
  PromptsSlugEditRoute: typeof PromptsSlugEditRoute
  SkillsSlugEditRoute: typeof SkillsSlugEditRoute
  TeamIdActivityRoute: typeof TeamIdActivityRoute
  TeamIdSettingsRoute: typeof TeamIdSettingsRoute
  UUsernameActivityRoute: typeof UUsernameActivityRoute
  WorkflowsSlugEditRoute: typeof WorkflowsSlugEditRoute
  BlogAdminIndexRoute: typeof BlogAdminIndexRoute
  CollectionsIdIndexRoute: typeof CollectionsIdIndexRoute
  PromptKitsSlugIndexRoute: typeof PromptKitsSlugIndexRoute
  PromptsSlugIndexRoute: typeof PromptsSlugIndexRoute
  SkillsSlugIndexRoute: typeof SkillsSlugIndexRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
  WorkflowsSlugIndexRoute: typeof WorkflowsSlugIndexRoute
  BlogAdminPostsNewRoute: typeof BlogAdminPostsNewRoute
  BlogAdminPostsIndexRoute: typeof BlogAdminPostsIndexRoute
  BlogAdminPostsIdEditRoute: typeof BlogAdminPostsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-from-menerio': {
      id: '/create-from-menerio'
      path: '/create-from-menerio'
      fullPath: '/create-from-menerio'
      preLoaderRoute: typeof CreateFromMenerioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-kits/new': {
      id: '/prompt-kits/new'
      path: '/prompt-kits/new'
      fullPath: '/prompt-kits/new'
      preLoaderRoute: typeof PromptKitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/new': {
      id: '/prompts/new'
      path: '/prompts/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof PromptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/wizard': {
      id: '/prompts/wizard'
      path: '/prompts/wizard'
      fullPath: '/prompts/wizard'
      preLoaderRoute: typeof PromptsWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/join': {
      id: '/team/join'
      path: '/team/join'
      fullPath: '/team/join'
      preLoaderRoute: typeof TeamJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/': {
      id: '/blog/admin/'
      path: '/blog/admin'
      fullPath: '/blog/admin/'
      preLoaderRoute: typeof BlogAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/categories': {
      id: '/blog/admin/categories'
      path: '/blog/admin/categories'
      fullPath: '/blog/admin/categories'
      preLoaderRoute: typeof BlogAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/media': {
      id: '/blog/admin/media'
      path: '/blog/admin/media'
      fullPath: '/blog/admin/media'
      preLoaderRoute: typeof BlogAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/tags': {
      id: '/blog/admin/tags'
      path: '/blog/admin/tags'
      fullPath: '/blog/admin/tags'
      preLoaderRoute: typeof BlogAdminTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id/': {
      id: '/collections/$id/'
      path: '/collections/$id'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof CollectionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id/edit': {
      id: '/collections/$id/edit'
      path: '/collections/$id/edit'
      fullPath: '/collections/$id/edit'
      preLoaderRoute: typeof CollectionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug/edit': {
      id: '/library/$slug/edit'
      path: '/library/$slug/edit'
      fullPath: '/library/$slug/edit'
      preLoaderRoute: typeof LibrarySlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug/versions': {
      id: '/library/$slug/versions'
      path: '/library/$slug/versions'
      fullPath: '/library/$slug/versions'
      preLoaderRoute: typeof LibrarySlugVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-kits/$slug/': {
      id: '/prompt-kits/$slug/'
      path: '/prompt-kits/$slug'
      fullPath: '/prompt-kits/$slug/'
      preLoaderRoute: typeof PromptKitsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-kits/$slug/edit': {
      id: '/prompt-kits/$slug/edit'
      path: '/prompt-kits/$slug/edit'
      fullPath: '/prompt-kits/$slug/edit'
      preLoaderRoute: typeof PromptKitsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug/': {
      id: '/prompts/$slug/'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug/'
      preLoaderRoute: typeof PromptsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug/edit': {
      id: '/prompts/$slug/edit'
      path: '/prompts/$slug/edit'
      fullPath: '/prompts/$slug/edit'
      preLoaderRoute: typeof PromptsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug/': {
      id: '/skills/$slug/'
      path: '/skills/$slug'
      fullPath: '/skills/$slug/'
      preLoaderRoute: typeof SkillsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug/edit': {
      id: '/skills/$slug/edit'
      path: '/skills/$slug/edit'
      fullPath: '/skills/$slug/edit'
      preLoaderRoute: typeof SkillsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/activity': {
      id: '/team/$id/activity'
      path: '/team/$id/activity'
      fullPath: '/team/$id/activity'
      preLoaderRoute: typeof TeamIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/settings': {
      id: '/team/$id/settings'
      path: '/team/$id/settings'
      fullPath: '/team/$id/settings'
      preLoaderRoute: typeof TeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/activity': {
      id: '/u/$username/activity'
      path: '/u/$username/activity'
      fullPath: '/u/$username/activity'
      preLoaderRoute: typeof UUsernameActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$slug/': {
      id: '/workflows/$slug/'
      path: '/workflows/$slug'
      fullPath: '/workflows/$slug/'
      preLoaderRoute: typeof WorkflowsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$slug/edit': {
      id: '/workflows/$slug/edit'
      path: '/workflows/$slug/edit'
      fullPath: '/workflows/$slug/edit'
      preLoaderRoute: typeof WorkflowsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/posts/': {
      id: '/blog/admin/posts/'
      path: '/blog/admin/posts'
      fullPath: '/blog/admin/posts/'
      preLoaderRoute: typeof BlogAdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/posts/new': {
      id: '/blog/admin/posts/new'
      path: '/blog/admin/posts/new'
      fullPath: '/blog/admin/posts/new'
      preLoaderRoute: typeof BlogAdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/posts/$id/edit': {
      id: '/blog/admin/posts/$id/edit'
      path: '/blog/admin/posts/$id/edit'
      fullPath: '/blog/admin/posts/$id/edit'
      preLoaderRoute: typeof BlogAdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CookiesRoute: CookiesRoute,
  CreateFromMenerioRoute: CreateFromMenerioRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRoute,
  ImpressumRoute: ImpressumRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CollectionsNewRoute: CollectionsNewRoute,
  ProfileEditRoute: ProfileEditRoute,
  PromptKitsNewRoute: PromptKitsNewRoute,
  PromptsNewRoute: PromptsNewRoute,
  PromptsWizardRoute: PromptsWizardRoute,
  SkillsNewRoute: SkillsNewRoute,
  TeamJoinRoute: TeamJoinRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  BlogIndexRoute: BlogIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  BlogAdminCategoriesRoute: BlogAdminCategoriesRoute,
  BlogAdminMediaRoute: BlogAdminMediaRoute,
  BlogAdminTagsRoute: BlogAdminTagsRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
  CollectionsIdEditRoute: CollectionsIdEditRoute,
  LibrarySlugEditRoute: LibrarySlugEditRoute,
  LibrarySlugVersionsRoute: LibrarySlugVersionsRoute,
  PromptKitsSlugEditRoute: PromptKitsSlugEditRoute,
  PromptsSlugEditRoute: PromptsSlugEditRoute,
  SkillsSlugEditRoute: SkillsSlugEditRoute,
  TeamIdActivityRoute: TeamIdActivityRoute,
  TeamIdSettingsRoute: TeamIdSettingsRoute,
  UUsernameActivityRoute: UUsernameActivityRoute,
  WorkflowsSlugEditRoute: WorkflowsSlugEditRoute,
  BlogAdminIndexRoute: BlogAdminIndexRoute,
  CollectionsIdIndexRoute: CollectionsIdIndexRoute,
  PromptKitsSlugIndexRoute: PromptKitsSlugIndexRoute,
  PromptsSlugIndexRoute: PromptsSlugIndexRoute,
  SkillsSlugIndexRoute: SkillsSlugIndexRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
  WorkflowsSlugIndexRoute: WorkflowsSlugIndexRoute,
  BlogAdminPostsNewRoute: BlogAdminPostsNewRoute,
  BlogAdminPostsIndexRoute: BlogAdminPostsIndexRoute,
  BlogAdminPostsIdEditRoute: BlogAdminPostsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
