
INSERT INTO public.moderation_stopwords (word, category, severity) VALUES
-- Sexual content
('porn', 'sexual', 'block'),
('pornography', 'sexual', 'block'),
('xxx', 'sexual', 'block'),
('hentai', 'sexual', 'block'),
('erotic', 'sexual', 'block'),
('erotica', 'sexual', 'block'),
('nude', 'sexual', 'block'),
('nudes', 'sexual', 'block'),
('naked', 'sexual', 'block'),
('orgasm', 'sexual', 'block'),
('masturbat', 'sexual', 'block'),
('blowjob', 'sexual', 'block'),
('handjob', 'sexual', 'block'),
('deepthroat', 'sexual', 'block'),
('anal sex', 'sexual', 'block'),
('oral sex', 'sexual', 'block'),
('gangbang', 'sexual', 'block'),
('threesome', 'sexual', 'block'),
('fetish', 'sexual', 'block'),
('bondage', 'sexual', 'block'),
('dildo', 'sexual', 'block'),
('vibrator', 'sexual', 'block'),
('cumshot', 'sexual', 'block'),
('creampie', 'sexual', 'block'),
('milf', 'sexual', 'block'),
('onlyfans', 'sexual', 'block'),
('sexting', 'sexual', 'block'),
('camgirl', 'sexual', 'block'),
('stripper', 'sexual', 'block'),
('escort service', 'sexual', 'block'),
('brothel', 'sexual', 'block'),
('prostitut', 'sexual', 'block'),
('sex slave', 'sexual', 'block'),
('child porn', 'sexual', 'block'),
('underage', 'sexual', 'block'),
('pedophil', 'sexual', 'block'),
('lolicon', 'sexual', 'block'),
-- Hate speech
('nigger', 'hate', 'block'),
('nigga', 'hate', 'block'),
('faggot', 'hate', 'block'),
('kike', 'hate', 'block'),
('chink', 'hate', 'block'),
('spic', 'hate', 'block'),
('wetback', 'hate', 'block'),
('gook', 'hate', 'block'),
('raghead', 'hate', 'block'),
('towelhead', 'hate', 'block'),
('tranny', 'hate', 'block'),
('retard', 'hate', 'block'),
('white power', 'hate', 'block'),
('white supremac', 'hate', 'block'),
('heil hitler', 'hate', 'block'),
('sieg heil', 'hate', 'block'),
('kill all', 'hate', 'block'),
('gas the', 'hate', 'block'),
('ethnic cleansing', 'hate', 'block'),
('genocide', 'hate', 'block'),
-- Malware / malicious
('rm -rf', 'malware', 'block'),
('format c:', 'malware', 'block'),
('reverse shell', 'malware', 'block'),
('keylogger', 'malware', 'block'),
('ransomware', 'malware', 'block'),
('trojan horse', 'malware', 'block'),
('sql injection', 'malware', 'block'),
('xss attack', 'malware', 'block'),
('phishing', 'malware', 'block'),
('credential harvesting', 'malware', 'block'),
-- Spam
('buy now', 'spam', 'block'),
('click here to win', 'spam', 'block'),
('free money', 'spam', 'block'),
('make money fast', 'spam', 'block'),
('nigerian prince', 'spam', 'block')
ON CONFLICT (word) DO NOTHING;
